app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [
   
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/soil-data/<uuid:land_id>/', views.soil_data, name='soil-data'),
    path('dashboard/soil-data/<uuid:land_id>/<slug:date>/', views.soil_data_by_date, name='soil-data-by-date'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('lands/', views.lands, name='lands'),
    path('add-land/', views.add_land, name='add-land'),
    path('edit-land/<uuid:land_id>/', views.edit_land, name='edit-land'),
    path('delete-land/<uuid:land_id>/', views.delete_land, name='delete-land'),
    path('maps/', views.maps, name='maps'),
    path('suggestion/', views.suggestion, name='suggestion'),
    path('suggestion/get-suggestion/<uuid:land_id>/', views.get_suggestion, name='get-suggestion'),
]

smart_agro/urls.py
from django.contrib import admin
from django.urls import path, include
from smart_agro.core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('service/', views.service),
    path('about/', views.about),
    path('contact/', views.contact),
    path('admin/', admin.site.urls),
    path('soil-data/', views.SoilDataView.as_view()),
    path('crops-suggestion/', views.CropsSuggestionView.as_view()),
    path("", include("authentication.urls")),  # add this
    path("", include("app.urls"))  # add this
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smart_agro/core/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
import uuid
# Create your models here


def profile_image_upload_to(instance, filename):
    return 'profile_images/%s/%s' % (instance.user.username, filename)

class Farmer(models.Model):
    user = models.OneToOneField(User, default=None,on_delete=models.CASCADE, related_name='farmer')
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    name = models.CharField(max_length=30)
    profile_image = models.ImageField(upload_to= profile_image_upload_to, blank=True, default="profile_images/blank-profile-picture.png")
    phone = models.CharField(max_length=15)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=100, blank=True, default='')
    city = models.CharField(max_length=30, blank=True, default='')
    country = models.CharField(max_length=30, blank=True, default='')
    postal_code = models.IntegerField(blank=True, default=-1)
    about_me = models.CharField(max_length=300, blank=True, default='')

    def __str__(self):
        return str(self.user.email)

class Land(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    farmer = models.ManyToManyField(Farmer, related_name="lands")
    name = models.CharField(max_length=30, blank=True, default='')
    area = models.FloatField()
    currentCrops = models.CharField(max_length=30, blank=True, default='')
    address = models.CharField(max_length=50, blank=True, default='')

    def __str__(self):
        return str(self.name) + " (" + str(self.id) + ")"

class SoilData(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    land = models.ForeignKey(Land, on_delete=models.CASCADE)
    time = models.DateTimeField(default=datetime.now)
    N = models.IntegerField()
    P = models.IntegerField()
    K = models.IntegerField()
    S = models.IntegerField()
    pH = models.FloatField()
    moisture = models.IntegerField()


    def __str__(self):
        return self.land.__str__() +" (" + self.time.strftime('%I:%M:%S %p, %d-%m-%Y') +")"

class CropsData(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    crops_name = models.CharField(max_length=30, blank=True, default='')
    N = models.IntegerField()
    t_N = models.IntegerField()
    P = models.IntegerField()
    t_P = models.IntegerField()
    K = models.IntegerField()
    t_K = models.IntegerField()
    S = models.IntegerField()
    t_S = models.IntegerField()
    pH = models.FloatField()
    t_pH = models.FloatField()
    moisture = models.IntegerField()
    t_moisture = models.IntegerField()

    def __str__(self):
        return str(self.crops_name) + " (" + str(self.id) + ")"

smart_agro/core/views.py
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .models import SoilData, Land, CropsData
from .serializers import SoilDataSerializer, LandSerializer, FarmerSerializer
from .utils import SubtractionMatrix,getCropsSuggestion
from django.shortcuts import render

def index(request):
    return render(request,'index.html',)

def service(request):
    return render(request,'service.html')

def about(request):
    return render(request,'about.html')

def contact(request):
    return render(request,'contact.html')

class SoilDataView(APIView):
    def get(self, request):
        try:
            soil_data_objects = SoilData.objects.filter(land=request.query_params.get('land')).order_by('-time')
            serializer = SoilDataSerializer(soil_data_objects, many=True)
            return Response(serializer.data)
        except:
            return Response({'success': False, 'message': 'land not found!', 'status': 404}, status=status.HTTP_404_NOT_FOUND)

    def post(self, request):
        serializer = SoilDataSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class CropsSuggestionView(APIView):
    def get(self, request):

        try:
            
            data = getCropsSuggestion(request.query_params.get('land'))

            return Response({'success': True,
                             'message': 'get crops suggestions',
                             'status': 200,
                             'data': data},status=status.HTTP_200_OK)
        except:
            return Response({'success': False, 'message': 'land not found!', 'status': 404},
                            status=status.HTTP_404_NOT_FOUND)

core/templates/add-land.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<!-- Header -->
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
  style="min-height: 400px;  background-size: cover; background-position: center top;">
  <!-- style="min-height: 250px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;"> -->
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <!-- <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">
            <h1 class="display-2 text-white">Hello {{ request.user.username }}</h1>
            <p class="text-white mt-0 mb-5">You can change your valuable information, You can change your valuable information...</p>
            <a href="#!" class="btn btn-info">Edit profile</a>
          </div>
        </div>
      </div> -->
</div>

<div class="container-fluid mt--8 mb-5">
  <div class="row">
    <div class="col-xl-12 order-xl-1">
      <div class="card bg-secondary shadow">
        <div class="row">
          <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
              <div class="card-header border-0">
                <div class="row align-items-center">
                  <div class="col">
                    <h3 class="mb-0">Add Land</h3>
                  </div>
                </div>
              </div>
              <div class="card-body">

                <form method="POST">
                  {% csrf_token %}
                  <h6 class="heading-small text-muted mb-4">Land Information</h6>
                  <div class="pl-lg-4">
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="form-group">
                          <label class="form-control-label" for="input-username">Name</label>
                          <input type="text" id="id_name" name="name" class="form-control form-control-alternative"
                            placeholder="Land Name" maxlength="30" required >
                        </div>
                      </div>
                      <div class="col-lg-6">
                        <div class="form-group">
                          <label class="form-control-label" for="input-email">Area</label>
                          <input type="number" step="any" id="id_area" name="area" class="form-control form-control-alternative"
                            placeholder="Land Area" required>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="form-group">
                          <label class="form-control-label" for="input-first-name">Current Crops</label>
                          <input type="text" id="id_currentCrops" name="currentCrops" class="form-control form-control-alternative"
                            placeholder="Current Crops Name" maxlength="30">
                        </div>
                      </div>
                      <div class="col-lg-6">
                        <div class="form-group">
                          <label class="form-control-label" for="input-last-name">Address</label>
                          <input type="text" id="id_address" name="address" class="form-control form-control-alternative"
                            placeholder="Land Address" maxlength="50" >
                        </div>
                      </div>
                    </div>
                  </div>


                  <div class="text-center">
                    <button type="submit" class="btn btn-success">Submit</a>
                  </div>
                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include "includes/footer.html" %}
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
{% endblock javascripts %}

core/templates/dashboard.html
{% extends 'layouts/base.html' %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Header -->
{% include "includes/header.html" %}

<div class="container-fluid mt--7 mb-5">

  <div class="row mb-5">
    <div class="col-xl-12">
      <div class="card shadow">
        <div class="card-header bg-transparent">
          <div class="row mb-3 align-items-center justify-content-between">
            <div class="col-4">
              <h3 class="mb-0">Soid Data Overview</h3>
            </div>
            <div class="col-8 text-right">
              <div class="dropdown">
                
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                  aria-haspopup="false" aria-expanded="false">
                  {% if selected_land %}
                  {{selected_land.name}}
                  {% else %}
                  Select Your Land
                  {% endif %}
                </button>
                <input class="btn" type="button" id="datepicker" value="{% if selected_date %}
                {{selected_date}}
                {% else %}
                {%  now "d-m-Y"%}
                {% endif %}" onclick="show_dp();">
                  </input>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  {% for land in lands %}
                  <a class="dropdown-item" href="{% url 'soil-data' land.id %}" id>{{land.name}}</a>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

          <div class="row mb-5">
            <div class="col-xl-6 mb-5 mb-xl-0">
              <div class="card bg-gradient-default-chart shadow">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <!-- <h6 class="text-uppercase text-light ls-1 mb-1">Overview</h6> -->
                      <h2 class="text-green mb-0">Moisture</h2>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    {% if soil_data.mos %}
                    <canvas id="chart-mos" class="chart-canvas"></canvas>
                    {% else %}
                    <h3 class="centered-div"> No Data </h3>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

            <div class="col-xl-6 mb-5 mb-xl-0">
              <div class="card bg-gradient-default-chart shadow">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <!-- <h6 class="text-uppercase text-light ls-1 mb-1">Overview</h6> -->
                      <h2 class="text-green mb-0">pH</h2>
                    </div>
                   
                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    {% if soil_data.pH %}
                    <canvas id="chart-ph" class="chart-canvas"></canvas>
                    {% else %}
                    <h3 class="centered-div"> No Data </h3>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row mb-5">
            <div class="col-xl-6 mb-5 mb-xl-0">
              <div class="card bg-gradient-default-chart shadow">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <!-- <h6 class="text-uppercase text-light ls-1 mb-1">Overview</h6> -->
                      <h2 class="text-green mb-0">Nitrogen</h2>
                    </div>
                   
                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    {% if soil_data.N %}
                    <canvas id="chart-n" class="chart-canvas"></canvas>
                    {% else %}
                    <h3 class="centered-div"> No Data </h3>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

            <div class="col-xl-6 mb-5 mb-xl-0">
              <div class="card bg-gradient-default-chart shadow">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <!-- <h6 class="text-uppercase text-light ls-1 mb-1">Overview</h6> -->
                      <h2 class="text-green mb-0">Phosphorus</h2>
                    </div>

                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    {% if soil_data.P %}
                    <canvas id="chart-p" class="chart-canvas"></canvas>
                    {% else %}
                    <h3 class="centered-div"> No Data </h3>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>


          <div class="row mb-5">
            <div class="col-xl-6 mb-5 mb-xl-0">
              <div class="card bg-gradient-default-chart shadow">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <!-- <h6 class="text-uppercase text-light ls-1 mb-1">Overview</h6> -->
                      <h2 class="text-green mb-0">Potassium</h2>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    {% if soil_data.K %}
                    <canvas id="chart-k" class="chart-canvas"></canvas>
                    {% else %}
                    <h3 class="centered-div"> No Data </h3>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

          </div>


        </div>
      </div>
    </div>
  </div>
</div>

{% include "includes/footer.html" %}
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>

$(function() {
    $( "#datepicker" ).datepicker({
      dateFormat: "dd-mm-yy",
    onSelect: function(dateText, inst) {
      window.location.href = "/dashboard/soil-data/{{selected_land.id}}/"+dateText;

    }
})
  });
  
  function show_dp(){
      $( "#datepicker" ).datepicker('show'); //Show on click of button
     }

//
// soil data chart
//

var soil_data_chart = (function() {

// Variables

var $chart_ph = $('#chart-ph');
var $chart_mos = $('#chart-mos');
var $chart_n = $('#chart-n');
var $chart_p = $('#chart-p');
var $chart_k = $('#chart-k');


function init_ph($chart) {

  var phChart = new Chart($chart, {
    type: 'line',
    options: {
      scales: {
        yAxes: [{
          gridLines: {
            lineWidth: 1,
            color: Charts.colors.gray[900],
            zeroLineColor: Charts.colors.gray[900]
          },
          ticks: {
            beginAtZero: true,
            stepSize: 2,
            max: 14,
            min: 0,
            callback: function(value, index, values) {
              return (index < 15) ? value : null;
            }
          }
        }]
      },
      tooltips: {
        callbacks: {
          label: function(item, data) {
            var label = data.datasets[item.datasetIndex].label || '';
            var yLabel = item.yLabel;
            var content = '';

            if (data.datasets.length > 1) {
              content += '<span class="popover-body-label mr-auto">' + label + '</span>';
            }

            content += '<span class="popover-body-value">pH: ' + yLabel;
            return content;
          }
        }
      }
    },
    data: {
      labels: ['3 AM', '6 AM', '9 AM', '12 PM','3 PM','6 PM','9 PM','12 AM' ],
      datasets: [{
        label: 'pH',
        data: {{soil_data.pH|safe}},
      }]
    }
  });

};


function init_mos($chart) {

  var mosChart = new Chart($chart, {
    type: 'line',
    options: {
      scales: {
        yAxes: [{
          gridLines: {
            lineWidth: 1,
            color: Charts.colors.gray[900],
            zeroLineColor: Charts.colors.gray[900]
          },
          ticks: {
            beginAtZero: true,
            stepSize: 20,
            max: 100,
            min: 0,
            callback: function(value, index, values) {
              return (index < 101) ? value : null;
            }
          }
        }]
      },
      tooltips: {
        callbacks: {
          label: function(item, data) {
            var label = data.datasets[item.datasetIndex].label || '';
            var yLabel = item.yLabel;
            var content = '';

            if (data.datasets.length > 1) {
              content += '<span class="popover-body-label mr-auto">' + label + '</span>';
            }

            content += '<span class="popover-body-value">mos: ' + yLabel +' %' +'</span>';
            return content;
          }
        }
      }
    },
    data: {
      labels: ['3 AM', '6 AM', '9 AM', '12 PM','3 PM','6 PM','9 PM','12 AM'  ],
      datasets: [{
        label: 'Moisture',
        data: {{soil_data.mos|safe}}
      }]
    }
  });

};

function init_NPK($chart, data) {

  var salesChart = new Chart($chart, {
    type: 'line',
    options: {
      scales: {
        yAxes: [{
          gridLines: {
            lineWidth: 1,
            color: Charts.colors.gray[900],
            zeroLineColor: Charts.colors.gray[900]
          },
          ticks: {
            min: 0,
            callback: function(value) {
              if (!(value % 10)) {
                return value;
              }
            }
          }
        }]
      },
      tooltips: {
        callbacks: {
          label: function(item, data) {
            var label = data.datasets[item.datasetIndex].label || '';
            var yLabel = item.yLabel;
            var content = '';

            if (data.datasets.length > 1) {
              content += '<span class="popover-body-label mr-auto">' + label + '</span>';
            }

            content += '<span class="popover-body-value">' + yLabel + '</span>';
            return content;
          }
        }
      }
    },
    data: {
      labels: [ '3 AM', '6 AM', '9 AM', '12 PM','3 PM','6 PM','9 PM','12 AM'  ],
      datasets: [{
        label: 'NPK',
        data: data
      }]
    }
  });

};




if ($chart_ph.length) {
  init_ph($chart_ph);
}
if ($chart_mos.length) {
  init_mos($chart_mos);
}
if ($chart_n.length) {
  init_NPK($chart_n,{{soil_data.N|safe}});
}
if ($chart_p.length) {
  init_NPK($chart_p,{{soil_data.P|safe}});
}
if ($chart_k.length) {
  init_NPK($chart_k,{{soil_data.K|safe}});
}

})();

</script>

{% endblock javascripts %}

core/templates/edit-land.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<!-- Header -->
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center"
    style="min-height: 400px;  background-size: cover; background-position: center top;">
    <!-- style="min-height: 250px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;"> -->
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <!-- Header container -->
    <!-- <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">
            <h1 class="display-2 text-white">Hello {{ request.user.username }}</h1>
            <p class="text-white mt-0 mb-5">You can change your valuable information, You can change your valuable information...</p>
            <a href="#!" class="btn btn-info">Edit profile</a>
          </div>
        </div>
      </div> -->
</div>

<div class="container-fluid mt--8 mb-5">
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="row">
                    <div class="col-xl-12 mb-5 mb-xl-0">
                        <div class="card shadow">
                            <div class="card-header border-0">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h3 class="mb-0">Edit Land</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">

                                <form method="POST">
                                    {% csrf_token %}
                                    <h6 class="heading-small text-muted mb-4">Land Information</h6>
                                    <div class="pl-lg-4">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input-username">Name</label>
                                                    <input type="text" id="id_name" name="name"
                                                        class="form-control form-control-alternative"
                                                        placeholder="Land Name" value="{{land.name}}" maxlength="30"
                                                        required>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input-email">Area</label>
                                                    <input type="number" step="any" id="id_area" name="area"
                                                        class="form-control form-control-alternative"
                                                        placeholder="Land Area" value="{{land.area}}" required>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input-first-name">Current
                                                        Crops</label>
                                                    <input type="text" id="id_currentCrops" name="currentCrops"
                                                        class="form-control form-control-alternative"
                                                        placeholder="Current Crops Name" value="{{land.currentCrops}}"
                                                        maxlength="30">
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label"
                                                        for="input-last-name">Address</label>
                                                    <input type="text" id="id_address" name="address"
                                                        class="form-control form-control-alternative"
                                                        placeholder="Land Address" value="{{land.address}}"
                                                        maxlength="50">
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="text-center">
                                        <button type="submit" class="btn btn-success">Submit</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include "includes/footer.html" %}
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

core/templates/error-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="/">Home</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/error-500.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 500      
              </div>

              <div class="text-center mb-4">
                Server error, please contact support<a href="/">Home</a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/maps.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock title %}

{% block content %}

    {% include "includes/header.html" %}

    <div class="container-fluid mt--7 mb-5">

      <div class="row">
        <div class="col">
          <div class="card shadow border-0">
            <div id="map-canvas" class="map-canvas" data-lat="40.748817" data-lng="-73.985428" style="height: 600px;"></div>
          </div>
        </div>
      </div>
    </div>


{% include "includes/footer.html" %}
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
{% endblock javascripts %}